### ISSUE TITLE
nav container implementation as nested view

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#493]
hi @oblomov-dev 

im trying to implement nav container as nested view of the recent pr control toolpage,

it seems not to work as expected..
i figured it will work with other layout type control besides flexible column layout..

here is my demo of it..

[demo_88.txt](https://github.com/abap2UI5/abap2UI5/files/12352760/demo_88.txt)

when pressing the Application nav button it supposed to destory all pages and insert new page, the nested view.

Edit:
maybe it worth a shot to try using the method “to”.
most of the navigation control have it and it also gives us transition animations when moving between views..

https://sapui5.hana.ondemand.com/sdk/#/api/sap.f.FlexibleColumnLayout%23methods/to

https://sapui5.hana.ondemand.com/sdk/#/api/sap.m.NavContainer%23methods/to

**Comment by choper725** [comment]
hi @oblomov-dev 
this demo is working for me,
but when i try to make it work on the icon tab header, its not working.. does it suppose to work like that only ?

here is my demo of what im trying to do..
[demo_89.txt](https://github.com/abap2UI5/abap2UI5/files/12362050/demo_89.txt)

**Comment by choper725** [comment]
great ill take a look, sorry for all the questions btw..

**Comment by choper725** [comment]
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/35502095-e8ca-48e7-96f6-a8c3557869cc)

im getting this in demo 89

**Comment by oblomov-dev** [comment]
fixed!

Harmonized parameter naming of _event and _event_client

**Comment by choper725** [comment]
still getting the same error..

**Comment by oblomov-dev** [comment]
<img width="600" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/dd0b38e8-6e5c-4fa8-a75e-bfca1adeb1d5">

https://github.com/abap2UI5/abap2UI5-samples/blob/353c253e24f6a2aabef60dce2b9595532a1b9ec9/src/z2ui5_cl_app_demo_89.clas.abap#L131

this time i am sure it works

**Comment by choper725** [comment]
demo still not working.. i think something changed,, it seems like my old snippet.. not the one with the event on the icon tab header..

**Comment by oblomov-dev** [comment]
89 there was a still a bug, updated again but now 88/89 both working on my side.

**Comment by choper725** [comment]
yes. now both are working... thanks..

should combine them i think btw.. they are pretty much the same..
