### ISSUE TITLE
unbind functionality

### ISSUE THREAD

**Issue by choper725** [abap2UI5/abap2UI5#586]
hi @oblomov-dev 

is there a way to unbind a binded value ?

the error i have is not finding a bind for a value.

the scenario is :
i run a flexible column layout when a nested view is a seperated class returning a xml view object to the main class.

once im switching between classes the binded attributes in t_attri table in method search_bind is looking for binds in the previous called class

**Comment by oblomov-dev** [comment]
Hi @choper725 

Yes in general this should be no problem. Is there a chance that you share this example? Then I can check what is the best way to solve this situation.

Best regards

**Comment by choper725** [comment]
yes ill do it

**Comment by choper725** [comment]
@oblomov-dev here are the demo files:

[CLASS A.txt](https://github.com/abap2UI5/abap2UI5/files/13032657/CLASS.A.txt)
[CLASS A_B.txt](https://github.com/abap2UI5/abap2UI5/files/13032660/CLASS.A_B.txt)
[CLASS A_B_C.txt](https://github.com/abap2UI5/abap2UI5/files/13032662/CLASS.A_B_C.txt)

here is a simple example:
CLASS A calls on press to class A_B which have  a binded value called MV_CLASS_1.

upon switching to CLASS A_B_C an error happen as in image
![image](https://github.com/abap2UI5/abap2UI5/assets/129428114/b3f294b7-3e98-4a9a-aa62-d3acfea3f015)

hence the request for unbinding functionality..

**Comment by oblomov-dev** [comment]
Thanks, I will check this out

**Comment by oblomov-dev** [comment]
Added your example to the samples repository:
z2ui5_cl_demo_app_104
z2ui5_cl_demo_app_105
z2ui5_cl_demo_app_112

Feel free to change it, that i can see the exact functionality you need.

Added now the following method:
_bind_clear
It clear just everything and is easy to understand. Not sure if we need more granular unbind functionality or if this creates just more complexity?

Adjusted the demos, the example is now working.
<img width="500" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/071d039f-a556-4d1c-8a4c-d0a277047d1b">

PS: You are functionality goes into the direction of SAP GUI Subscreen Logic. I like this and also tried some things out in this direction! Combining Apps where certain apps can be reused as subscreens again and again can be a very efficient approach in the development process. 💪

**Comment by choper725** [comment]
hi @oblomov-dev 

yes thats exacly what i had in mind doing all the generic class reuse approach,

if i understand correctly _bind_clear deletes all bindes in the current app, 
i think this might cause an issue as if we use reusable class in a main class app,
even the binds in the main class app gets deleted which will create incomptabilities down the road..

maybe an option for bind clear for specific bind will do the trick ??

**Comment by oblomov-dev** [comment]
ok i corrected the method, now you can import the specific data and the entry in the table will be deleted. 
<img width="658" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/69d7a23f-c119-4257-aae9-bb92096c02db">

**Comment by choper725** [comment]
great ill check !
so that makes it that this bind clear method should be written in the reusable class if i guess right?

**Comment by oblomov-dev** [comment]
Try to call it like this (don't import the name, use the variable instead):
client->_bind_clear( MV_CLASS_1 )

There is also no need to do it necessarily in the subapp, just call the method with importing parameter subapp->mv_class_1 in the main app.

Don't know if I am clear enough, feel free to update the demos in the samples repository with your changes and send a PR. Then i can later check this again.

**Comment by choper725** [comment]
still not working, with sending as the variable and not a string of it.

`      DATA(lv_name) = 'MO_HANDLER->MS_DB-APP' && lr_bind->name.
      ASSIGN (lv_name) TO <attri>.

      IF sy-subrc = 0.    `

this code above not getting sy-subrc = 0, no matter what it do.

**Comment by oblomov-dev** [comment]
ok i updated the functionality again, the demo is running now (continuing creates an error but this is an error in the demo)

<img width="1512" alt="image" src="https://github.com/abap2UI5/abap2UI5/assets/102328295/4b340f4d-c15f-4774-a300-332cf4ab7ba8">

**Comment by choper725** [comment]
hi @oblomov-dev 
still something not working correctly in the demo..

seems the bind clear method not deleting the bind..

**Comment by oblomov-dev** [comment]
yes the binding functionality is the most comlicated of abap2UI5, a lot of different side effects to keep in mind. but in genereal reusable components architecture is possible, it just maybe will take a little bit till we find the correct behaviour for all use cases.

i updated the demos again, now i don't get any error anymore. which functionality do you need more? feel free to adjust the demo.

i think in your change the problem was, that you forgot to set that the variable to status not_dissolved again with:
mo_handler->ms_db-t_attri[ name = val ]-check_dissolved = abap_false.

**Comment by choper725** [comment]
closing this as this seems to be resolved, thx @oblomov-dev
